name: instaclone
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image_picker: ^1.1.2
  cached_network_image: ^3.2.2
  eva_icons_flutter: ^3.1.0

  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

